language: python

matrix:
  fast_finish: true
  include:

    - python: 2.7
      env:
        - COVERAGE=false
    - python: 3.3
      env:
        - COVERAGE=false
    - python: 3.4
      env:
        - COVERAGE=false
    - python: 3.5
      env:
        - COVERAGE=false
    - python: 3.6
      env:
        - COVERAGE=true

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update conda --yes  

install:
  - conda create --name testenv --yes python=$TRAVIS_PYTHON_VERSION pip six nose
  - source activate testenv
  - pip install coveralls codecov
  - pip install .

script:
  - nosetests --with-coverage --cover-package=metar --verbose

after_success:
  - if [ ${COVERAGE} = true ]; then coveralls; fi
  - if [ ${COVERAGE} = true ]; then codecov; fi
